import styles from "@/styles/Home.module.css";
import { Switch } from "antd";
import { Inter } from "next/font/google";
import Head from "next/head";
import React, { useState } from "react";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [toggle, setToggle] = useState(false);

  const toggler = () => {
    toggle ? setToggle(false) : setToggle(true);
  };

  return (
    <>
      <Head>
        <title>Nutriplan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>Nutriplan</header>
      <main className={styles.main}>
        <section className={styles.body}>
          <div className={styles.dietary}>
            <div>
              <div>Gluten Free: </div>
              <div className={styles.toggle}>
                <Switch onclick={toggler} />
              </div>
            </div>
            <div>
              <div>Soy Free: hi</div>
              <div className={styles.toggle}>
                <Switch onclick={toggler} />
              </div>
            </div>
            <div>
              <div>Dairy Free: </div>
              <div className={styles.toggle}>
                <Switch onclick={toggler} />
              </div>
            </div>
            <div>
              <div>Seafood Free: </div>
              <div className={styles.toggle}>
                <Switch onclick={toggler} />
              </div>
            </div>
            <div>
              <div>Nut Free: </div>
              <div className={styles.toggle}>
                <Switch onclick={toggler} />
              </div>
            </div>
          </div>
          <div className={styles.macros}>
            <p>Enter your daily desired caloric intake: </p>
            <input></input>
            <p>Enter your daily desired protein intake: </p>
            <input></input>
          </div>
        </section>
        <section className={styles.goButton}>
          <button>Make my Recommendation!</button>
        </section>
      </main>
    </>
  );
}
